<?php
require_once 'includes/layout.php';
$creators = $pdo->query("SELECT u.username,up.creator_level,up.creator_rank,up.creator_exp,
    (SELECT COUNT(*) FROM user_follows f WHERE f.followed_id=u.id) AS followers,
    (SELECT COUNT(*) FROM video_views vv INNER JOIN videos v ON v.id=vv.video_id WHERE v.user_id=u.id) AS views
    FROM user_progression up INNER JOIN users u ON u.id=up.user_id
    WHERE up.creator_exp > 0
    ORDER BY (up.creator_level * 20 + followers * 1.5 + views * 0.02) DESC LIMIT 50")->fetchAll();
$viewers = $pdo->query("SELECT u.username,up.viewer_level,up.viewer_rank,up.viewer_exp FROM user_progression up INNER JOIN users u ON u.id=up.user_id WHERE up.viewer_exp>0 ORDER BY up.viewer_exp DESC LIMIT 50")->fetchAll();
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Leaderboards</title><link rel="stylesheet" href="public/styles.css"></head><body><?php renderTopbar('Christube',['index.php'=>'Home','trending.php'=>'Trending','search.php'=>'Search','leaderboard.php'=>'Leaderboards']); ?><div class="page"><main class="main"><div class="panel"><h1>Community Leaderboards</h1><p class="tiny">Rankings balance progression, trust-oriented activity, and engagement quality signals.</p></div><div class="panel"><h2>Top Creators</h2><?php if(!$creators): ?><p class="muted">No creator data yet.</p><?php else: ?><table><tr><th>Creator</th><th>Tier</th><th>EXP</th><th>Followers</th><th>Views</th></tr><?php foreach($creators as $c): ?><tr><td><a href="profile.php?u=<?php echo urlencode($c['username']); ?>">@<?php echo e($c['username']); ?></a></td><td><?php echo e($c['creator_rank']); ?> (Lv <?php echo (int)$c['creator_level']; ?>)</td><td><?php echo (int)$c['creator_exp']; ?></td><td><?php echo (int)$c['followers']; ?></td><td><?php echo (int)$c['views']; ?></td></tr><?php endforeach; ?></table><?php endif; ?></div><div class="panel"><h2>Top Community Members</h2><?php if(!$viewers): ?><p class="muted">No viewer progression yet.</p><?php else: ?><table><tr><th>User</th><th>Rank</th><th>EXP</th></tr><?php foreach($viewers as $v): ?><tr><td><a href="profile.php?u=<?php echo urlencode($v['username']); ?>">@<?php echo e($v['username']); ?></a></td><td><?php echo e($v['viewer_rank']); ?> (Lv <?php echo (int)$v['viewer_level']; ?>)</td><td><?php echo (int)$v['viewer_exp']; ?></td></tr><?php endforeach; ?></table><?php endif; ?></div></main></div></body></html>
