<?php
require_once '../includes/layout.php';
requireLogin();
$userId=(int)$_SESSION['user_id'];
$range=(string)($_GET['range'] ?? '28d');
if(!in_array($range,['7d','28d','lifetime'],true))$range='28d';
$analytics = getCreatorAnalytics($pdo,$userId,$range);
?>
<!doctype html><html><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>Creator Analytics</title><link rel="stylesheet" href="../public/styles.css"></head><body><?php renderTopbar('Creator Studio', creatorNav('../')); ?><div class="page"><main class="main"><div class="panel"><h1>Analytics Overview</h1><form method="get"><select name="range"><option value="7d" <?php echo $range==='7d'?'selected':''; ?>>Last 7 Days</option><option value="28d" <?php echo $range==='28d'?'selected':''; ?>>Last 28 Days</option><option value="lifetime" <?php echo $range==='lifetime'?'selected':''; ?>>Lifetime</option></select><button>Apply</button></form><p class="tiny"><?php echo e($analytics['range_label']); ?></p><p>Views: <?php echo (int)$analytics['views']; ?> · Watch starts: <?php echo (int)$analytics['watch_starts']; ?> · Likes: <?php echo (int)$analytics['likes']; ?> · Comments: <?php echo (int)$analytics['comments']; ?> · Followers gained: <?php echo (int)$analytics['follows_gained']; ?></p><p>Avg watch seconds: <?php echo number_format((float)$analytics['avg_watch_seconds'],1); ?> · Completion rate: <?php echo number_format(((float)$analytics['completion_rate'])*100,1); ?>%</p></div><div class="panel"><h2>Recent Performance Trend</h2><?php if(!$analytics['series']): ?><p class="muted">Not enough data yet.</p><?php else: ?><table><tr><th>Date</th><th>Views</th></tr><?php foreach($analytics['series'] as $row): ?><tr><td><?php echo e($row['day']); ?></td><td><?php echo (int)$row['views']; ?></td></tr><?php endforeach; ?></table><?php endif; ?></div><div class="panel"><h2>Top Videos</h2><?php if(!$analytics['top_videos']): ?><p class="muted">No top videos yet.</p><?php else: ?><ul><?php foreach($analytics['top_videos'] as $tv): ?><li><a href="../v.php?s=<?php echo urlencode($tv['slug']); ?>"><?php echo e($tv['title']); ?></a> · <?php echo (int)$tv['views']; ?> views · <a href="video_analytics.php?id=<?php echo (int)$tv['id']; ?>">details</a></li><?php endforeach; ?></ul><?php endif; ?></div></main></div></body></html>
